var phrasesLibrary = function() {    
    var phrases = [
        { id: 1, author: 'Demóstenes', phrase: 'Pequenas oportunidades são muitas vezes o princípio de grandes empreendimentos' },
        { id: 2, author: 'Autor Desconhecido', phrase: 'Quase sempre que a empresa ou a mídia falam do morro ou das favelas, é com tom depreciativo aos seus moradores' },
        { id: 3, author: 'Coelho Neto', phrase: 'A valentia sem um ideal que a enobreça degrada-se em ferocidade' },
        { id: 4, author: 'Cid Cercal', phrase: 'É preferível saber poucas coisas muito bem a saber muitas coisas muito mal' },
        { id: 5, author: 'Autor Desconhecido', phrase: 'A satisfação de quebrar os padrões' },
        { id: 6, author: 'Roberto das Neves', phrase: 'A utopia é o ponto de partida de todo progresso e o germe de um melhor futuro' },
        { id: 7, author: 'Adágio Popular', phrase: 'Bom conselho desprezado, há de ser muito lembrado' },
        { id: 9, author: 'Vicente Avelino', phrase: 'Há uma coisa mais cruel do que descrer de tudo: em tudo acreditar' },
        { id: 10, author: 'Autor Desconhecido', phrase: 'Carregar sempre a energia com um gesto ou uma prece antes de qualquer encontro com pessoas' },
        { id: 12, author: 'Joaquim Nabuco', phrase: 'A consciência é o último ramo da alma que floresce: só dá frutos tardios' },
        { id: 13, author: 'Liturgia', phrase: 'Os neurônios desenvolvidos com calma, com mansidão, são os neurônios do bem' },
        { id: 14, author: 'Afonso Duarte de Barros', phrase: 'A imaginação é o áureo cordel a tecer a fria realidade que nos cerca, talvez o nada que nos espera' },
        { id: 15, author: 'Papa Francisco', phrase: 'O idoso quer passar adiante os valores adquiridos' },
        { id: 16, author: 'Menotti Del Picchia', phrase: 'O coração da gente é como uma casa que não pode ficar vazia' },
        { id: 17, author: 'Autor Desconhecido', phrase: 'Cuidado para não rotular o idoso. Rotulando, fica mais fácil de criticar e até de excluir' },
        { id: 18, author: 'José de Alencar', phrase: 'Só a ignorância aceita e a indiferença tolera o reinado da mediocridade' },
        { id: 19, author: 'Autor Desconhecido', phrase: 'As ideias são para expor. Não para impor' },
        { id: 20, author: 'Neves Manta', phrase: 'A mulher de dezesseis anos é na vida um botão de rosa; e o homem de dezoito, no máximo, o tato agreste do cajazeiro impetuoso' },
        { id: 21, author: 'Glória Kalil', phrase: 'Panelinha arruina o grupo e tenta manipular psicologicamente o grupo. É bulling' },
        { id: 22, author: 'Juscelino Kubitsche', phrase: 'Sereis tanto mais influentes quanto mais fordes corretos e justos' },
        { id: 23, author: 'A. Austregésio', phrase: 'Todas as fórmulas para a vida feliz repousam em um ideal superior' },
        { id: 24, author: 'Autor Desconhecido', phrase: 'Quando tudo gira em torno do dinheiro, até as pessoas viram mercadoria' },
        { id: 25, author: 'Câmara Cascudo', phrase: 'Comparar é sempre mais cômodo porque estabelece a referência e com ela a compreensão' },
        { id: 26, author: 'Autor Desconhecido', phrase: 'O político é um mandatário e o eleitor seu mandante. Portanto, todo filiado partidário deve saber sua doutrina' },
        { id: 27, author: 'Marquês de Maricá', phrase: 'Os velhos ruminam o pretérito, os moços antecipam e devoram o futuro' },
        { id: 28, author: 'Autor Desconhecido', phrase: 'Toda conversa tem o mesmo valor. Do porteiro do prédio ao presidente da empresa' },
        { id: 29, author: 'Mesquita Pimentel', phrase: 'Para subirmos à montanha da santidade, precisamos começar por descer o vale da humildade' },
        { id: 30, author: 'Eloide Borges Pacheco', phrase: 'A função de um Coral é se preparar e aguardar para ser solicitado e reconhecido' },
        { id: 31, author: 'Clóvis Bevilácqua', phrase: 'A inteligência irmanada com a força de vontade e com a esperança, produz uma ideia' },
        { id: 32, author: 'Eloide Borges Pacheco', phrase: 'Palavra com veneno faz mal para quem profere e para quem ouve' },
        { id: 33, author: 'Afrânio Peixoto', phrase: 'Não se mede o bem-estar ou a felicidade que se tem, senão pelo que ainda falta' },
        { id: 34, author: 'Eloide Borges Pacheco', phrase: 'Pode fazer projetos, mas deixe espaço para as coisas que poderão entrar' },
        { id: 35, author: 'Eloide Borges Pacheco', phrase: 'Não é diminuindo o outro que a gente cresce' },
        { id: 36, author: 'Marquês de Maricá', phrase: 'Os mais arrojados em falar são ordinariamente os menos profundos em saber' },
        { id: 37, author: 'Eloide Borges Pacheco', phrase: 'A gente se torna mais forte quando faz o outro maior' },
        { id: 38, author: 'Eloide Borges Pacheco', phrase: 'Fazer sempre menos (ou o que puder) com mais qualidade' },
        { id: 39, author: 'Autor Desconhecido', phrase: 'A fé são só duas letrinhas. Mas tem um poder imenso' },
        { id: 40, author: 'Antero de Figueiredo', phrase: 'Os erros são proveitosos quando nos educam' },
        { id: 41, author: 'Cleidir', phrase: 'Sempre se deve dar um passinho a frente' },
        { id: 42, author: 'Masaharu Taniguchi', phrase: 'A vida adulta será resultado daquilo que recebemos até os 5 anos de idade. Depois poderemos nos adaptar ao meio, mas conforme a personalidade da infância, poderemos ser mais ou menos felizes' },
        { id: 43, author: 'Camilo Castelo Branco', phrase: 'A infância é a estação das crenças, dos temores e das superstições' },
        { id: 44, author: 'Autor Desconhecido', phrase: 'Paciência porque a misericórdia de Deus está com você' },
        { id: 45, author: 'Vanicza', phrase: 'A gente não pára de sonhar porque envelhece. Envelhece porque pára de sonhar' },
        { id: 46, author: 'Eloide Borges Pacheco', phrase: 'Sei que minha natureza é divina e Deus habita em mim, estimulando-me todo instante e que seu amor caminha na minha frente, iluminando todas as minhas decisões' },
        { id: 47, author: 'Tomaz Magalhães', phrase: 'Não quero que tenham pena de mim. Quero, sim, ser forte o suficiente para ajudar a quem precisar de mim' },
        { id: 48, author: 'Massaharo Taniguchi', phrase: 'O esforço para reverenciar alguém difícil de ser amado, é um grande meio para elevar a alma' },
        { id: 49, author: 'Oswaldo Cruz', phrase: 'Pelas faltas dos outros, o homem sensato corrige as suas' },
        { id: 50, author: 'Autor Desconhecido', phrase: 'Participe mais dos movimentos sócio culturais. Cultura é tudo aquilo que nos faz parar, pensar e melhorar' },
        { id: 51, author: 'Dr. Amoroso', phrase: 'Nós estamos encarregados de manter a cultura viva' }
    ];
     return function get() {
        var number = Math.floor(Math.random()*phrases.length);
        return phrases[number];
    };
}